.\" Copyright (c) 2019-2021 Miki Hermann & Gernot Salzer
.TH mcp-uniq 1 "2021-08-10" "1.04" "MCP System"
.
.SH NAME
mcp-uniq -- elimination of rows with the same value but different leading
group identifiers in a matrix.
.
.SH SYNOPSIS
.B mcp-uniq
.RI [\| "OPTION" "\|]\|.\|.\|."
.
.SH DESCRIPTION
.PP
Takes a matrix and deletes rows with the same value but different leading
group identifiers.
.
.SH OPTIONS
.
.TP
\fB\-i\fR, \fB\-\-input\fI input-file
File with a matrix, as it was produced e.g. by \fImcp-trans\fR.
.IP
Default: STDIN.
.
.TP
\fB\-o\fR, \fB\-\-output\fI output-file
Matrix file with unique rows.
.IP
Default: STDOUT or \fIbasename\fR of \fIinput-file\fR with \fI.unq\fR suffix.
.
.TP
\fB\-\-hash \fRyes | no
Should mcp-uniq use hash for storing rows?
.IP
yes:
Use hash to store rows.
.IP
no:
Use direct code to store rows.
.IP
Default: yes.
.
.PP
.
.
.SH SEE ALSO
mcp-check(1),
mcp-guess(1),
mcp-trans(1),
mcp-split(1),
mcp-seq(1),
mcp-mpi(1),
mcp-pthread(1),
mcp-hybrid(1),
mcp-sparse(1),
mcp-predict(1)
.
.SH BUGS
There are certanly some.
.
.SH AUTHORS
Miki Hermann <hermann@lix.polytechnique.fr>
.br
Gernot Salzer <gernot.salzer@tuwien.ac.at>
