.\" Copyright (c) 2019-2021 Miki Hermann & Gernot Salzer
.TH mcp-clean 1 "2024-08-19" "1.04" "MCP System"
.
.SH NAME
mcp-clean - cleaning of data from outliers using a meta description
.
.SH SYNOPSIS
.B mcp-clean
.RI [\| "OPTION" "\|]\|.\|.\|."
.
.SH DESCRIPTION
.PP
The data is cleaned using a meta descitption. The resulting file is
ready to be used as input for the MCP core.
.
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-input\fI input-file
Input file to be cleaned. The input file must be specified.
.
.TP
\fB\-o\fR, \fB\-\-output\fI output-file
Output file of cleaned data, ready to be used by the MCP core.
.IP
Default: STDOUT.
.
.TP
\fB\-m\fR, \fB\-\-meta\fI meta-file
Description of the structure of the \fIinput-file\fR containing
cleaning instructions. Format of the \fImeta-file\fR is described
in \fBmcp-clean\fR(5).
.
.
.SH SEE ALSO
mcp-trans(5),
mcp-guess(1),
mcp-split(1),
mcp-seq(1),
mcp-mpi(1),
mcp-pthread(1),
mcp-hybrid(1),
mcp-check(1),
mcp-sparse(1),
mcp-chk2tst(1),
mcp-predict(1)
.
.SH BUGS
There are certanly some.
.
.SH AUTHORS
Miki Hermann <hermann@lix.polytechnique.fr>
.br
Gernot Salzer <gernot.salzer@tuwien.ac.at>
.br
Oskar Dabkowski
