.\" Copyright (c) 2019-2021 Miki Hermann & Gernot Salzer
.TH mcp-compare 1 "2025-04-11" "1.04" "MCP System"
.
.SH NAME
mcp-compare -- comparing original file with prediction
.
.SH SYNOPSIS
.B mcp-compare
.RI [\| "OPTION" "\|]\|.\|.\|."
.
.SH DESCRIPTION
.PP
Takes a transformed file or a check file with leading group
identifiers and copares it with prediction file produced after
application of \fImcp-chk2tst\fR and \fImcp-predict\fR
.
.SH OPTIONS
.
.TP
\fB\-or\fR, \fB\-\-original\fI transformed or check file.
Check file \fI.chk\fR as it was produced e.g. by \fImcp-split\fR.
Transformed file \fI.mat\fR as it was produced e.g. by \fImcp-trans\fR.
.IP
Default: none.
.
.TP
\fB\-pdx\fR, \fB\-\-prediction\fI prediction file.

Prediction file \fI.pdx\fR  as it was produced e.g. by \fImcp-predict\fR.
.IP
Default: \fIbasename\fR of \fIoriginal file\fR with \fI.pdx\fR suffix.
.
.TP
\fB\-o\fR, \fB\-\-output\fI output-file
Check file with leading group identifiers deleted.
.IP
Default: \fIbasename\fR of \fIoriginal file\fR with \fI-compare.txt\fR suffix.
.
.PP
.
.
.SH SEE ALSO
mcp-trans(1),
mcp-split(1),
mcp-chk2tst(1),
mcp-predict(1),
.
.SH BUGS
There are certanly some.
.
.SH AUTHORS
Miki Hermann <hermann@lix.polytechnique.fr>
.br
Gernot Salzer <gernot.salzer@tuwien.ac.at>
