.\" Copyright (c) 2019-2021 Miki Hermann & Gernot Salzer
.TH mcp-trans 5 "2021-03-10" "1.04" "MCP System"
.
.SH NAME
mcp-trans \- meta-file syntax
.
.SH DESCRIPTION
.PP
The \fImeta-file\fR is a text file that describes the structure of the
original file which will be binarized, as well as the binarization
style of each coordinate.
.PP
White space can be freely introduced among the commands. Everything
beginning with the symbol \fB#\fR until the end of line is a
comment. Each transformation command terminates by the sign \fB;\fR
(semicolon).
.PP
Each transformation command has the following form:
.PP
.in +4n
.EX
.IB "identifier " = " coordinate " : " indicator " ;
.EE
.in
.PP
The symbols \fB=\fR, \fB:\fR, and \fB;\fR are syntactic sugar for a
better orientation of the parser. The attribute \fIidentifier\fR (a string) will
become the name of the variable for the given \fIcoordinate\fR (an
integer). The \fIindicator\fR has one of the following forms.
.PP
.in +4n
.EX
.B concept
.B pivot
.B \fBbool\fR	'[' \fIelem_0 elem_1\fR ']'
.B \fBenum\fR	'[' \fIelem\fR\|.\|.\|. ']'
.B \fBup\fR	'[' \fIelem\fR\|.\|.\|. ']'
.B \fBdown\fR	'[' \fIelem\fR\|.\|.\|. ']'
.B \fBint\fR	\fImin max\fR
.B \fBdj\fR	\fIn min max\fR
.B \fBcp\fR	['-inf'] \fInumber\fR\|.\|.\|. ['+inf']
.B \fBover\fR	\fIn min max l\fR
.B \fBspan\fR	\fIl min max\fR
.B \fBwarp\fR	\fIl0 min max l1\fR
.EE
.in
.PP
where the semantics of these indicators is described below. The
elements \fIelem\fR are arbitrary strings, \fImin\fR, \fImax\fR, and
\fInumber\fR are
numeric values; \fIn\fR, \fIl\fR, \fIl0\fR, and \fIl1\fR are positive
integer values.
.TP 7
.B concept
This is the learned concept. The corresponding \fIconcept\fR identifier will
become the group prefix.
.TP
.B pivot
This is the pivot identifier. The corresponding \fIidentifier\fR will
become the pivot value.
.TP
.B bool
Boolean two-element set.
.TP
.B enum
Enumerated set of elements.
.TP
.B up
Enumerated set of increasing elements.
.TP
.B down
Enumerated set of decreasing elements.
.TP
.B int
Integers in the range between \fImin\fR and \fImax\fR.
.TP
.B dj
Continuous interval [\fImin\fR, \fImax\fR) cut into \fIn\fR disjoint
chunks.
.TP
.B cp
Intervals determined by checkpoints. The \fInumber\fRs must build an increasing sequence.
Consecutive numbers \fIa\fR and \fIb\fR determine the interval [\fIa\fR, \fIb\fR).
The optional tokens \fI-inf\fR and \fI+inf\fR stand for minimal and maximal infinity, respectively.
.IP
Example: BMI = 5: cp -inf 16.0 17.0 18.5 25.0 30.0 35.0 40.0 +inf;
.TP
.B over
Continuous interval [\fImin\fR, \fImax\fR) cut into \fIn\fR chunks
with overlaps of length \fIl\fR.
.TP
.B span
Continuous interval [\fImin\fR, \fImax\fR) cut into disjoint chunks,
each of length \fIl\fR.
.TP
.B warp
Continuous interval [\fImin\fR, \fImax\fR) cut into chunks of length
\fIl0\fR, with overlaps of length \fIl1\fR.
.
.SH SEE ALSO
mcp-trans(1)
.
.SH BUGS
There are certanly some.
.
.SH AUTHORS
Miki Hermann <hermann@lix.polytechnique.fr>
.br
Gernot Salzer <gernot.salzer@tuwien.ac.at>
