.\" Copyright (c) 2019-2021 Miki Hermann & Gernot Salzer
.TH mcp-XXX 1 "2021-XX-XX" "1.04" "MCP System"
.
.SH NAME
mcp-XXX -- what it is
.
.SH SYNOPSIS
mcp-XXX how is it called
.
.SH DESCRIPTION
.PP
Describe what you want
.
.SH OPTIONS
.TP
--option
.PP
See whatever
.
.
.SH SEE ALSO
mcp-YYY
.
.SH BUGS
There are certanly some.
.
.SH AUTHORS
Miki Hermann <hermann@lix.polytechnique.fr>
.br
Gernot Salzer <gernot.salzer@tuwien.ac.at>
