.\" Copyright (c) 2019-2021 Miki Hermann & Gernot Salzer
.TH mcp-clean 5 "2024-08-20" "1.04" "MCP System"
.
.SH NAME
mcp-clean \- meta-file syntax
.
.SH DESCRIPTION
.PP
The \fImeta-file\fR is a text file that describes the structure of the
original input file which will be cleaned and/or restrained to a subset.
.PP
White space can be freely introduced among the commands. Everything
beginning with the symbol \fB#\fR until the end of line is a
comment. Each transformation command terminates by the sign \fB;\fR
(semicolon).
.PP
Each transformation command has the following form:
.PP
.in +4n
.EX
.IB "columns " : " type_operation " ;
.EE
.in
or
.in +4n
.EX
.IB "number " : " " \fBconcept\fR " ";
.EE
.in
.PP
The former describes the \fItype operation\fR which will be applied to data
within the specified \fIcolumns\fR.
The latter, with the keyword \fBconcept\fR,
describes the data column on which reside the \fIconcept\fR values.
.PP
The symbols \fB=\fR, \fB:\fR, and \fB;\fR are syntactic sugar for a
better orientation of the parser.
.PP
The \fIcolumns\fR can be either a single \fInumber\fR or an interval of numbers
.PP
.in +4n
.EX
.IB "number " .. " number"
.EE
.in
.PP
The \fItype operation\fR is either an expression
.PP
.in +4n
.EX
.IB "type " = " operation"
.EE
.in
.PP
or an expression
.PP
.in +4n
.EX
\fBstring =\fR \fIregular_expression\fR
.EE
.in
.PP
The former describes the data \fItype\fR with the operation
which will be performed on it.
The latter, with the keyword \fBstring\fR, describes the
\fIregular expression\fR which the data must satisfy.
.PP
The data \fItype\fR has three forms:
.PP
.in +4n
.EX
.B int\fR to specify an \fIinteger\fR
.B nat\fR to specify a \fInon-negative integer\fR
.B real\fR to specify a \fIreal number\fR
.EE
.in
.PP
The \fIoperation\fR is either specified by \fIintervals\fR or
one of the following keywords, specifying the interval around
the mean data value,  which the data must satisfy
.PP
.in +4n
.EX
.B 1sigma\fR for \fIone\fR standard deviation length on each side
.B 2sigma\fR for \fItwo\fR standard deviation length on each side
.B 3sigma\fR for \fIthree\fR standard deviation length on each side
.EE
.in
.PP
The \fIintervals\fR are a disjunction of unit intervals separated by
the operator \fB||\fR or only one unit interval. A \fIunit interval\fR
is either an \fIinteger interval\fR or a \fIreal interval\fR.
.PP
An \fIinteger interval\fR is an expression
.PP
.in +4n
.EX
\fIinteger\fR \fB..\fR \fIinteger\fR
.EE
.in
.PP
specifying all integers included in the interval,
where \fB..\fR is a double-dot special symbol.
A \fIreal interval\fR is an expression
.PP
.in +4n
.EX
\fIleft-hand_side\fR \fIreal\fR \fB..\fR \fIreal\fR \fIright-hand_side\fR
.EE
.in
.PP
where the \fIleft-hand side\fR is one of the symbols \fB(\fR or \f[\R, and
\fIright-hand side\fR is one of the symbols \fB)\fR or \fB]\fR,
as it is used for specifying open and closed sides of an interval.
.
.SH SEE ALSO
mcp-clean(1)
.
.SH BUGS
There are certanly some.
.
.SH AUTHORS
Miki Hermann <hermann@lix.polytechnique.fr>
.br
Gernot Salzer <gernot.salzer@tuwien.ac.at>
.br
Oskar Dabkowski
